### ISSUE TITLE
Ukedagnavn i hendelser

### ISSUE THREAD

**Issue by vongohren** [kjell-gunnar-midtlyng/rsvp-app#2]
Hei jeg savner ukedagnavn i hendelser. Greit å ha mulighet til å direkte se hvilken dag det er uten å måtte slå opp kalenderen. Man har en ca oversikt når datoen er, et ukes span, men ikke mer detaljert enn som så.

**Comment by charliemidtlyng** [comment]
Det er vel en kjapp fiks - kan se på det i helga.

**Comment by charliemidtlyng** [comment]
Lagt inn ukedagnavn nå.

**Comment by vongohren** [comment]
Smud
