### ISSUE TITLE
Bekreftelse på sletting

### ISSUE THREAD

**Issue by mykle90** [kjell-gunnar-midtlyng/rsvp-app#5]
La brukeren bekrefte sletting, når en trykker på "Avmeld". Feks. ved en "ok/cancel" prompt.

**Comment by charliemidtlyng** [comment]
+1

**Comment by EsbenAarz** [comment]
Ja takk. Presterte nettopp å avmelde en annen person. Jobber du på den @mykle90 , eller kan jeg begynne på den i nær fremtid?

**Comment by mykle90** [comment]
Branchen som heter iss5 har en enkel confirmdialog ved sletting. Burde kanskje vise navnet til deltakeren i confirmdialogen.

**Comment by mykle90** [comment]
iss5 oppdatert med navn i confirm dialog. Formatet er: "Vil du melde av {navn}?"
